// <auto-generated />
using System;
using FalknerCountyJuvenileCourt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FalknerCountyJuvenileCourt.Migrations
{
    [DbContext(typeof(CourtContext))]
    partial class CourtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Crime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DrugCourt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrugOffense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilingDecisionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntakeDecisionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JuvenileID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NameID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FilingDecisionID");

                    b.HasIndex("IntakeDecisionID");

                    b.HasIndex("JuvenileID");

                    b.HasIndex("NameID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Crime", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.CrimeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CrimeType", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.FilingDecision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FilingDecision", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Gender", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.IntakeDecision", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("IntakeDecision", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Juvenile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.HasIndex("RaceID");

                    b.HasIndex("RiskID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Juveniles", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Race", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Risk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Name")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Risk", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Crime", b =>
                {
                    b.HasOne("FalknerCountyJuvenileCourt.Models.FilingDecision", "FilingDecision")
                        .WithMany("Crimes")
                        .HasForeignKey("FilingDecisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.IntakeDecision", "IntakeDecision")
                        .WithMany("Crimes")
                        .HasForeignKey("IntakeDecisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.Juvenile", "Juvenile")
                        .WithMany("Crimes")
                        .HasForeignKey("JuvenileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.CrimeType", "Name")
                        .WithMany("Crimes")
                        .HasForeignKey("NameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolID");

                    b.Navigation("FilingDecision");

                    b.Navigation("IntakeDecision");

                    b.Navigation("Juvenile");

                    b.Navigation("Name");

                    b.Navigation("School");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Juvenile", b =>
                {
                    b.HasOne("FalknerCountyJuvenileCourt.Models.Gender", "Gender")
                        .WithMany("Juveniles")
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.Race", "Race")
                        .WithMany("Juveniles")
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.Risk", "Risk")
                        .WithMany("Juveniles")
                        .HasForeignKey("RiskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FalknerCountyJuvenileCourt.Models.School", null)
                        .WithMany("Juveniles")
                        .HasForeignKey("SchoolID");

                    b.Navigation("Gender");

                    b.Navigation("Race");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.CrimeType", b =>
                {
                    b.Navigation("Crimes");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.FilingDecision", b =>
                {
                    b.Navigation("Crimes");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Gender", b =>
                {
                    b.Navigation("Juveniles");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.IntakeDecision", b =>
                {
                    b.Navigation("Crimes");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Juvenile", b =>
                {
                    b.Navigation("Crimes");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Race", b =>
                {
                    b.Navigation("Juveniles");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.Risk", b =>
                {
                    b.Navigation("Juveniles");
                });

            modelBuilder.Entity("FalknerCountyJuvenileCourt.Models.School", b =>
                {
                    b.Navigation("Juveniles");
                });
#pragma warning restore 612, 618
        }
    }
}
